apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-deployment
  labels:
    app: aks-deployment
  namespace: namespace-workflow-1702046139402
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-deployment
  template:
    metadata:
      labels:
        app: aks-deployment
    spec:
      containers:
        - name: aks-deployment
          image: mycontainer05.azurecr.io/image-workflow-1702046139402:latest
          ports:
            - containerPort: 8080