apiVersion: v1
kind: Service
metadata:
  name: aks-deployment
  namespace: namespace-workflow-1702046139402
spec:
  type: LoadBalancer
  selector:
    app: aks-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080